### ISSUE TITLE
how to run model and use it

### ISSUE THREAD

**Issue by alinemati45** [uf-hobi-informatics-lab/GatorTron#4]
Hello,
I need to know how to load the model and run it?
even though, by searching online, I could not find any useful resource. 
I am new with NEMO.

thanks,

**Comment by ToneLi** [comment]
I  have tried the provided .pt file, but failed, if the authors can give an example of how to use their provided file, that is better.

**Comment by alinemati45** [comment]
Thank you for taking the time to consider my message. I am eager to apply the model based on my research, but I am currently awaiting a response from the authors.

**Comment by yonghuiwuf** [comment]
We are preparing a demo codes and will release the demo codes as soon as possible.

**Comment by yonghuiwuf** [comment]
GatorTron models are available from Hugging Face: https://huggingface.co/UFNLP

'How to use' codes was added to this repository as well as the Hugging Face repository.

**Comment by yonghuiwuf** [comment]
How to use code was provided.
