### ISSUE TITLE
How to run model and finetune it 

### ISSUE THREAD

**Issue by nageshpindi** [uf-hobi-informatics-lab/GatorTron#5]
Hi Guys,
I need to know how to load the GatorTron model and run it. GatorTron exactly matches with my requirement and i was in searching online but i could't find any useful resources. Can you please help me on this model, Thanks in advanced.

**Comment by bugface** [comment]
#4

**Comment by yonghuiwuf** [comment]
GatorTron models are available from Hugging Face: https://huggingface.co/UFNLP

'How to use' codes was added to this repository as well as the Hugging Face repository.
