### ISSUE TITLE
Example of generating text from gatortron model?

### ISSUE THREAD

**Issue by JustGitting** [uf-hobi-informatics-lab/GatorTron#7]
Hi,

I'm new to huggingface and gatortron. I wish to generate text from a medical description for example, but not sure how to do it with the gatortron models. I've tried to adapt other examples (e.g. [https://huggingface.co/docs/transformers/tasks/language_modeling](https://huggingface.co/docs/transformers/tasks/language_modeling) ) to the gatortron model, but have not had much luck. 

How can I use gatortron* for generating text?

```
from transformers import AutoTokenizer, AutoModelForCausalLM

prompt = "Somatic hypermutation allows the immune system to"

tokenizer = AutoTokenizer.from_pretrained('UFNLP/gatortronS')

inputs = tokenizer(prompt, return_tensors="pt").input_ids

model = AutoModelForCausalLM.from_pretrained('UFNLP/gatortronS', is_decoder=True)

outputs = model.generate(input_ids=inputs, max_new_tokens=100, do_sample=True, top_k=50, top_p=0.95, temperature=0.9)

tokenizer.batch_decode(outputs, skip_special_tokens=True)
```

I only get dots...

`['somatic hypermutation allows the immune system to ....................................................................................................']`

I've also tried the pipeline example:

```
prompt = "Somatic hypermutation allows the immune system to"
from transformers import pipeline

generator = pipeline("text-generation", model='UFNLP/gatortronS')
generator(prompt)
```

But it does not work either.

```
If you want to use `MegatronBertForCausalLM` as a standalone, add `is_decoder=True.`
Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.
/home/user1/.local/lib/python3.9/site-packages/transformers/generation/utils.py:1369: UserWarning: Using `max_length`'s default (20) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(

[{'generated_text': 'Somatic hypermutation allows the immune system to to to to to to to to to to to to to'}]
```

Thank you for your help and great project.

**Comment by VuTrungNguyen** [comment]
Any update on this? Have you tried fine-tuning the model? @JustGitting

**Comment by JustGitting** [comment]
Hi @VuTrungNguyen,

No, I have not progressed this because I was just spinning my wheels and hoped someone could put me in the right direction.

**Comment by alireza0r** [comment]
Hi @JustGitting,

I also encountered similar issues while trying to execute GatorTron (@VuTrungNguyen). Have you managed to make it work? If so, could you please share your insights or any solutions you've found?

Thanks a lot.

**Comment by JustGitting** [comment]
Hi @alireza0r 

Unfortunately no luck. I hope @bugface has time to help us, it would be greatly appreciated.

**Comment by bugface** [comment]
Please give us some time.  We will look at this issue and get back to you all.

**Comment by JustGitting** [comment]
Thank you @bugface! 🙏

**Comment by alireza0r** [comment]
Thank you @JustGitting 
Thank you @bugface , I look forward to the result :)

**Comment by bugface** [comment]
http://mayhewsw.github.io/2019/01/16/can-bert-generate-text/

so gatortron is encoder only model which cannot use .generate() method.  Please refer to the link above for how to generate text.  In general, this series models are good at NLU tasks like NER, RE, MRC but not generative tasks.

**Comment by JustGitting** [comment]
Thank you @bugface for clarifying the model capabilities! Thanks for the link too.
